sudo:required
services:
  - docker

script:
  docker build -t  akli-lachi/node2 .
  docker iamges  akli-lachi/node2 

befere_deploy:
  - docker login -u  <kali1803> -p <Celine2017>

deploy:
  provider: script
  script : docker push <kali1803/nore-test>
  on:
    branch: master